---
- name: Configure Web Application
  hosts: all
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install Apache web server
      package:
        name: apache2
        state: present
      become: yes

    - name: Ensure Apache is running and enabled
      service:
        name: apache2
        state: started
        enabled: yes
      become: yes

    - name: Deploy web application files
      copy:
        src: https://github.com/Niks2992/terraform-assignment/blob/main/index.html
        dest: https://github.com/Niks2992/terraform-assignment/tree/main/html
      become: yes
